language: node_js
install: npm install
script: npm run build
deploy:
  # See https://github.com/travis-ci/travis-ci/issues/9312
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
